apiVersion: skaffold/v4beta10
kind: Config
build:
  artifacts:
    - image: jorakhachatryan/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: jorakhachatryan/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: jorakhachatryan/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: jorakhachatryan/ticket-client
      context: client
      sync:
        manual:
          - src: '**.*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: jorakhachatryan/t_expiration
      context: expiration
      sync:
        manual:
          - src: '**.*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: jorakhachatryan/t_payments
      context: payments
      sync:
        manual:
          - src: '**.*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
deploy:
  kubectl: {}